### ISSUE TITLE
Use a relative path in the require statement of the library files

### ISSUE THREAD

**Issue by MatthewHager** [poetic/short-stack-osx#2]

**Comment by DanielOchoa** [comment]
There's no way to use relative path:

Every time the custom module is ran, the file where the ruby code resides is moved to a tmp directory - so any relative path requires will break. 

We can:
1. Keep using absolute path which will be prone to break if the project changes where it is downloaded to or the repo name changes
2. Add another step to the short-stack task installer to set the path on the ruby task files. (This opens the door to a lot of potential problems and unknowns)

That's all I got for now.

**Comment by MatthewHager** [comment]
The library is no longer in use so this is a non issue.
